export interface LetterTemplate {
  name: string;
  code: string;
  category: 'Surat Izin' | 'Surat Keterangan' | 'Lainnya' | 'Surat Kuasa & Administrasi';
  fields: string[]; // Custom inputs needed for this letter type
  placeholder?: string;
}

export const LETTER_CATALOG: LetterTemplate[] = [
  // --- SURAT IZIN ---
  { name: 'Surat Izin', code: 'SI', category: 'Surat Izin', fields: ['Tujuan Izin', 'Tanggal Pelaksanaan', 'Keterangan tambahan'] },
  { name: 'Surat Izin Suami (Keluarga)', code: 'SIS', category: 'Surat Izin', fields: ['Nama Suami', 'Pekerjaan Suami', 'Tujuan Izin Kerja/Pergi'] },
  { name: 'Surat Pernyataan Izin Suami', code: 'SPIS', category: 'Surat Izin', fields: ['Nama Suami', 'NIK Suami', 'Pernyataan Izin Keperluan'] },
  { name: 'Surat Izin Orang Tua', code: 'SIOT', category: 'Surat Izin', fields: ['Nama Ayah/Ibu', 'Pekerjaan Orang Tua', 'Tujuan Izin Anak'] },
  { name: 'Surat Izin Tidak Masuk Kerja', code: 'SITM', category: 'Surat Izin', fields: ['Nama Instansi/Perusahaan', 'Alasan Absen', 'Sakit/Keperluan Masuk Kerja'] },
  { name: 'Surat Izin Keramaian', code: 'SIK', category: 'Surat Izin', fields: ['Acara Keramaian', 'Tempat Kegiatan', 'Tanggal & Waktu Acara'] },
  { name: 'Surat Pernyataan Tanggung Jawab Mutlak', code: 'SPTJM', category: 'Surat Izin', fields: ['Uraian Tanggung Jawab', 'Dasar Pengajuan', 'Pernyataan Mutlak'] },
  { name: 'Surat Izin Usaha Mikro Kecil', code: 'SIUMK', category: 'Surat Izin', fields: ['Nama Usaha', 'Alamat Usaha', 'Modal Usaha (Rp)'] },
  { name: 'Surat dispensasi', code: 'SDSP', category: 'Surat Izin', fields: ['Keterangan Dispen', 'Instansi Tujuan', 'Batas Waktu Dispensasi'] },
  { name: 'Surat Ijin Tebang / Potong Pohon', code: 'SITP', category: 'Surat Izin', fields: ['Jenis Pohon', 'Lokasi Penebangan', 'Alasan Tebang'] },

  // --- SURAT KETERANGAN ---
  { name: 'Surat Keterangan Nikah (N1,N2,N3,N......)', code: 'SKN', category: 'Surat Keterangan', fields: ['Nama Calon Pasangan', 'Bin/Binti', 'Tempat Tanggal Lahir Pasangan'] },
  { name: 'Surat Keterangan Kelahiran (F-2.01)', code: 'SKKL-F', category: 'Surat Keterangan', fields: ['Nama Anak', 'Hari/Tanggal Lahir', 'Nama Ayah & Ibu'] },
  { name: 'Formulir Permohonan Pindah Desa', code: 'FPP-D', category: 'Surat Keterangan', fields: ['Jumlah Anggota Keluarga Pindah', 'Alamat Tujuan Pindah', 'Alasan Pindah'] },
  { name: 'Formulir Permohonan Pindah Kecamatan', code: 'FPP-K', category: 'Surat Keterangan', fields: ['Jumlah Anggota Keluarga Pindah', 'Alamat Tujuan Kecamatan', 'Alasan Pindah'] },
  { name: 'Formulir Permohonan Pindah Kabupaten', code: 'FPP-KB', category: 'Surat Keterangan', fields: ['Jumlah Anggota Keluarga Pindah', 'Alamat Tujuan Kabupaten', 'Alasan Pindah'] },
  { name: 'Formulir Permohonan Pindah Provinsi', code: 'FPP-P', category: 'Surat Keterangan', fields: ['Jumlah Anggota Keluarga Pindah', 'Alamat Tujuan Provinsi', 'Alasan Pindah'] },
  { name: 'Formulir Permohonan Pindah Masuk', code: 'FPPM', category: 'Surat Keterangan', fields: ['Alamat Asal', 'Alamat Tujuan di Desa', 'Jumlah Jiwa Pindah'] },
  { name: 'Formulir Pindah Dalam Satu Desa/Kelurahan', code: 'FPDS', category: 'Surat Keterangan', fields: ['Alamat Asal RT/RW', 'Alamat Baru RT/RW', 'Alasan Pindah'] },
  { name: 'Surat Keterangan Pindah Desa', code: 'SKP-D', category: 'Surat Keterangan', fields: ['Alamat Tujuan', 'Keluarga yang Pindah', 'Keterangan Tambahan'] },
  { name: 'Surat Keterangan Pindah Kecamatan', code: 'SKP-K', category: 'Surat Keterangan', fields: ['Kecamatan Tujuan', 'Keluarga yang Pindah', 'Alasan Pindah'] },
  { name: 'Surat Keterangan Pindah Kabupaten', code: 'SKP-KB', category: 'Surat Keterangan', fields: ['Kabupaten Tujuan', 'Keluarga yang Pindah', 'Alasan Pindah'] },
  { name: 'Surat Keterangan Pindah Provinsi', code: 'SKP-P', category: 'Surat Keterangan', fields: ['Provinsi Tujuan', 'Keluarga yang Pindah', 'Alasan Pindah'] },
  { name: 'Surat Keterangan Pindah Dalam Satu Desa/Kelurahan', code: 'SKPD', category: 'Surat Keterangan', fields: ['Dusun Asal', 'Dusun Tujuan', 'Alasan'] },
  { name: 'Surat Pengantar Pindah Desa', code: 'SPP-D', category: 'Surat Keterangan', fields: ['Alamat Tujuan Pindah', 'Kepentingan', 'Keluarga Ikut'] },
  { name: 'Surat Pengantar Pindah Kecamatan', code: 'SPP-K', category: 'Surat Keterangan', fields: ['Kecamatan Tujuan', 'Kepentingan', 'Keluarga Ikut'] },
  { name: 'Surat Pengantar Pindah Kabupaten', code: 'SPP-KB', category: 'Surat Keterangan', fields: ['Kabupaten Tujuan', 'Kepentingan', 'Keluarga Ikut'] },
  { name: 'Surat Pengantar Pindah Provinsi', code: 'SPP-P', category: 'Surat Keterangan', fields: ['Provinsi Tujuan', 'Kepentingan', 'Keluarga Ikut'] },
  { name: 'Surat Pengantar Pindah Dalam Satu Desa/Kelurahan', code: 'SPP-DS', category: 'Surat Keterangan', fields: ['RT Asal', 'RT Tujuan', 'Kepentingan'] },
  { name: 'Surat Pengantar Pindah Luar Negeri (F-2.59)', code: 'SPPLN', category: 'Surat Keterangan', fields: ['Negara Tujuan Pindah', 'Nama Sponsor', 'Waktu Tinggal'] },
  { name: 'Surat Keterangan Kematian (F-2.29)', code: 'SKKM-F', category: 'Surat Keterangan', fields: ['Nama Jenazah', 'Tanggal Wafat', 'Alasan Kematian', 'Saksi Kematian'] },
  { name: 'Surat Keterangan Asal - Usul', code: 'SKAU', category: 'Surat Keterangan', fields: ['Nama Orang Tua Asal', 'Status Tanah Asal', 'Keperluan Dokumen'] },
  { name: 'Surat Keterangan Tentang Orang Tua', code: 'SKOT', category: 'Surat Keterangan', fields: ['Nama Ayah/Ibu', 'NIK Orang Tua', 'Hubungan Keluarga'] },
  { name: 'Surat Pemberitahuan Kehendak Nikah', code: 'SPKN', category: 'Surat Keterangan', fields: ['Tanggal Rencana Nikah', 'Nama Pasangan', 'Lokasi KUA'] },
  { name: 'Surat Keterangan Kematian Suami/Istri', code: 'SKKS', category: 'Surat Keterangan', fields: ['Nama Almarhum/ah', 'Tanggal Wafat', 'Status Waris/Janda'] },
  { name: 'Surat Keterangan Andon Nikah', code: 'SKAN', category: 'Surat Keterangan', fields: ['Nama Calon Pasangan', 'Alamat KUA Tujuan Andon'] },
  { name: 'Surat Keterangan Usaha (belum berizin)', code: 'SKU-N', category: 'Surat Keterangan', fields: ['Nama Usaha', 'Jenis Komoditas', 'Lama Berdiri'] },
  { name: 'Surat Keterangan Usaha (memiliki izin)', code: 'SKU-Y', category: 'Surat Keterangan', fields: ['Nama Usaha', 'No Izin Legalitas', 'Alamat Usaha'] },
  { name: 'Surat Keterangan Tidak Mampu', code: 'SKTM-GEN', category: 'Surat Keterangan', fields: ['Keperluan SKTM', 'Nama Tanggungan', 'Penghasilan Maksimum'] },
  { name: 'Surat Keterangan Kejandaan', code: 'SKJD', category: 'Surat Keterangan', fields: ['Nama Mantan Suami', 'Sebab Cerai/Meninggal', 'Keterangan Anak'] },
  { name: 'Surat Pernyataan Wali Nikah', code: 'SPWN', category: 'Surat Keterangan', fields: ['Nama Wali', 'Hubungan Wali', 'Alasan Menjadi Wali'] },
  { name: 'Surat Keterangan Mahar', code: 'SKM', category: 'Surat Keterangan', fields: ['Jumlah Mahar/Emas', 'Nama Mempelai', 'Pemberian Mahar'] },
  { name: 'Surat Pengantar Kehilangan', code: 'SPK', category: 'Surat Keterangan', fields: ['Barang/Dokumen Hilang', 'Est. Tanggal Hilang', 'Tempat Kehilangan'] },
  { name: 'Surat Keterangan Penghasilan (perbulan)', code: 'SKHP', category: 'Surat Keterangan', fields: ['Nominal Gaji Pokok (Rp)', 'Pekerjaan Rinci', 'Instansi/Wiraswasta'] },
  { name: 'Surat Keterangan Taksir Tanah', code: 'SKTT', category: 'Surat Keterangan', fields: ['Luas Tanah (m2)', 'Sertifikat/C Desa', 'Taksiran Nilai Jual (Rp)'] },
  { name: 'Surat Keterangan Suami Istri', code: 'SKSI', category: 'Surat Keterangan', fields: ['Nama Suami', 'Nama Istri', 'Catatan Pernikahan'] },
  { name: 'Surat Keterangan Tebang Kayu', code: 'SKTK', category: 'Surat Keterangan', fields: ['Jenis Kayu', 'Jumlah Pohon', 'Pagar/Batas Lahan'] },
  { name: 'Surat Keterangan Tidak Memiliki Rumah', code: 'SKTMR', category: 'Surat Keterangan', fields: ['Keperluan Surat', 'Alamat Tinggal Sekarang'] },
  { name: 'Surat Keterangan Imigrasi', code: 'SKI', category: 'Surat Keterangan', fields: ['Paspor No', 'Negara Tujuan', 'Dinas Imigrasi'] },
  { name: 'Surat Keterangan Pembenaran Nama', code: 'SKPN', category: 'Surat Keterangan', fields: ['Nama di KTP', 'Nama di Dokumen Lain', 'Jenis Dokumen Beda'] },
  { name: 'Surat Keterangan Penghasilan Kuliah', code: 'SKPK', category: 'Surat Keterangan', fields: ['Nama Mahasiswa', 'Nominal Penghasilan Orang Tua (Rp)'] },
  { name: 'Surat Keterangan Buku C', code: 'SKBC', category: 'Surat Keterangan', fields: ['No Buku C Desa', 'Persil No', 'Kelas Klasifikasi Tanah'] },
  { name: 'Surat Keterangan Domisili Perusahaan', code: 'SKDP', category: 'Surat Keterangan', fields: ['Nama Perusahaan', 'NIB/Akte Pendirian', 'Jumlah Karyawan'] },
  { name: 'Surat Keterangan Beda Nama', code: 'SKBN', category: 'Surat Keterangan', fields: ['Nama Benar', 'Nama Salah', 'Tertulis di Dokumen'] },
  { name: 'Surat Keterangan Belum Pernah Menikah', code: 'SKBPM', category: 'Surat Keterangan', fields: ['Keperluan Surat', 'Nama Orang Tua Saksi'] },
  { name: 'Surat Keterangan Miskin', code: 'SKM-R', category: 'Surat Keterangan', fields: ['Jumlah Anggota Tanggungan', 'Kondisi Rumah Fisik', 'Penghasilan'] },
  { name: 'Surat Keterangan Bersih Diri', code: 'SKBD', category: 'Surat Keterangan', fields: ['Kebutuhan Instansi', 'Pekerjaan yang Dilamar'] },
  { name: 'Surat Keterangan Bidik Misi Lulus', code: 'SKBML', category: 'Surat Keterangan', fields: ['Nama Universitas', 'Program Studi', 'Prestasi Sekolah'] },
  { name: 'Surat Keterangan Pindah Sementara', code: 'SKPS', category: 'Surat Keterangan', fields: ['Kota Tujuan Sementara', 'Tujuan Kerja/Belajar', 'Masa Berlaku'] },
  { name: 'Surat Keterangan Akta Jual Beli Tanah', code: 'SKAJB', category: 'Surat Keterangan', fields: ['No Akta Jual Beli', 'Nama Pembeli', 'Luas Lahan Jual'] },
  { name: 'Surat Keterangan Beasiswa Kuliah Bidik Misi', code: 'SKBK-BM', category: 'Surat Keterangan', fields: ['NIM Mahasiswa', 'Fakultas', 'Nama Orang Tua Terkait'] },
  { name: 'Surat Keterangan Keringanan Sekolah', code: 'SKKS-S', category: 'Surat Keterangan', fields: ['Nama Sekolah/Madrasah', 'Nama Siswa/i', 'Alasan Keringanan'] },
  { name: 'Surat Keterangan Domisili Usaha', code: 'SKDU', category: 'Surat Keterangan', fields: ['Nama Usaha', 'Klasifikasi Bidang Usaha', 'Lokasi Usaha'] },
  { name: 'Surat Keterangan Tidak Mampu Sekolah', code: 'SKTM-S', category: 'Surat Keterangan', fields: ['Nama Siswa/i', 'Nama Sekolah', 'Kelas / Jurusan'] },
  { name: 'Surat Keterangan Domisili Lembaga', code: 'SKDL', category: 'Surat Keterangan', fields: ['Nama Lembaga/Yayasan', 'Akte Kemenkumham', 'Kegiatan Utama'] },
  { name: 'Surat Keterangan Tidak Mampu Bidik Misi', code: 'SKTM-BM', category: 'Surat Keterangan', fields: ['Nama Mahasiswa', 'Perguruan Tinggi', 'NIM/No Seleksi'] },
  { name: 'Surat Keterangan Tidak Mampu Kuliah', code: 'SKTM-K', category: 'Surat Keterangan', fields: ['Nama Mahasiswa', 'Nama Kampus', 'Fakultas/Prodi'] },
  { name: 'Surat Keterangan Tidak Mampu Jampersal', code: 'SKTM-J', category: 'Surat Keterangan', fields: ['Nama Ibu Hamil', 'Puskesmas Rujukan', 'Estimasi Lahir'] },
  { name: 'Surat Keterangan Domisili', code: 'SKD-GEN', category: 'Surat Keterangan', fields: ['Alamat Tinggal Sekarang', 'Keterangan Domisili Sejak'] },
  { name: 'Surat Keterangan Tidak Mampu PLN', code: 'SKTM-PLN', category: 'Surat Keterangan', fields: ['No ID Pelanggan PLN', 'Daya Listrik (VA)', 'Peruntukan Subsidi'] },
  { name: 'Surat Keterangan Umum', code: 'SKU-U', category: 'Surat Keterangan', fields: ['Keterangan Rinci', 'Tujuan Surat Pengantar'] },
  { name: 'Surat Keterangan Domisili (v2)', code: 'SKD-V2', category: 'Surat Keterangan', fields: ['Alamat Domisili Baru', 'Lama Tinggal', 'Rekomendasi RT/RW'] },
  { name: 'Surat Keterangan Domisili (Usia Lanjut/Renta)', code: 'SKD-UL', category: 'Surat Keterangan', fields: ['Nama Wali Pengurus', 'Kondisi Kesehatan', 'Tujuan Bantuan Lansia'] },
  { name: 'Surat Keterangan Domisili - Yayasan', code: 'SKD-Y', category: 'Surat Keterangan', fields: ['Nama Yayasan', 'Bidang Sosial/Keagamaan', 'Alamat Operasional'] },
  { name: 'Surat Keterangan Tinggal Bersama', code: 'SKTB', category: 'Surat Keterangan', fields: ['Nama Pemilik Rumah', 'Hubungan Kerabat', 'Jumlah Warga Tinggal'] },
  { name: 'Surat Keterangan Usaha (BANK)', code: 'SKU-B', category: 'Surat Keterangan', fields: ['Nama Usaha', 'Bank Tujuan Kredit', 'Angsuran/Modal Ajuan'] },
  { name: 'Surat Keterangan Ahli Waris', code: 'SKAW', category: 'Surat Keterangan', fields: ['Nama Pewaris (Meninggal)', 'Daftar Nama Ahli Waris', 'No Akte Kematian'] },
  { name: 'Surat Keterangan Ahli Waris (v2)', code: 'SKAW-V2', category: 'Surat Keterangan', fields: ['Nama Pewaris', 'Keterangan Notaris/Desa', 'Aset Warisan'] },
  { name: 'Surat Keterangan Kelahiran', code: 'SKK', category: 'Surat Keterangan', fields: ['Nama Bayi', 'Tempat/Tanggal Lahir', 'Nama Orang Tua'] },
  { name: 'Surat Keterangan Biodata', code: 'SKB', category: 'Surat Keterangan', fields: ['Nama Lengkap', 'Tempat Lahir', 'Agama', 'Pendidikan Terakhir'] },
  { name: 'Surat Keterangan Beda Biodata', code: 'SKBB', category: 'Surat Keterangan', fields: ['Nama di KTP/KK', 'Nama di Ijazah', 'Perbedaan yang Benar'] },
  { name: 'Surat Keterangan Perbedaan Data Agunan', code: 'SKPDA', category: 'Surat Keterangan', fields: ['No SHM/Sertifikat', 'Nama di Jaminan', 'Bank Pemberi Kredit'] },
  { name: 'Surat Keterangan Belum/Tidak mempunyai AKTA LAHIR', code: 'SKT-AL', category: 'Surat Keterangan', fields: ['Anak Ke-', 'Hari/Tanggal Lahir', 'Nama Ayah Ibu'] },
  { name: 'Surat Jalan', code: 'SJL', category: 'Surat Keterangan', fields: ['Kota Tujuan', 'Kendaraan/Pelat Nomor', 'Barang yang Dibawa'] },
  { name: 'Surat Keterangan Penelitian', code: 'SK-PL', category: 'Surat Keterangan', fields: ['Nama Peneliti', 'Kampus/Lembaga', 'Judul Penelitian'] },
  { name: 'Surat Keterangan Penghasilan Orang Tua', code: 'SKHP-OT', category: 'Surat Keterangan', fields: ['Nominal Gaji Ayah', 'Nominal Gaji Ibu', 'Pekerjaan Orang Tua'] },
  { name: 'Surat Keterangan Asal-usul Tanah', code: 'SKAUT', category: 'Surat Keterangan', fields: ['Asal Usul Hibah/Waris', 'Batas Utara/Selatan/Timur/Barat', 'Luas Lahan'] },
  { name: 'SKD (Surat Keterangan Desa)', code: 'SKD-RESMI', category: 'Surat Keterangan', fields: ['Keperluan Resmi', 'Keterangan Administratif'] },
  { name: 'Surat Pengantar Hewan Ternak Besar', code: 'SPHT', category: 'Surat Keterangan', fields: ['Jenis Hewan Ternak', 'Jumlah Ekor', 'Tujuan Pengiriman'] },
  { name: 'Surat Keterangan Pengantar Kayu', code: 'SKPKY', category: 'Surat Keterangan', fields: ['Volume Kayu (Kubik)', 'Jenis Kayu Olahan', 'Tujuan Kirim'] },
  { name: 'Surat Keterangan Perubahan Status Listrik', code: 'SKPSL', category: 'Surat Keterangan', fields: ['No Sambungan PLN', 'Perubahan Daya VA', 'Alasan Perubahan'] },
  { name: 'Surat Keterangan Pengambilan Dana Bantuan BSM', code: 'SKP-BSM', category: 'Surat Keterangan', fields: ['Nama Rekening Siswa', 'No Buku Tabungan BSM', 'Sekolah Asal'] },
  { name: 'Surat Keterangan berada Di Luar Kota ( Bekerja )', code: 'SKBLK', category: 'Surat Keterangan', fields: ['Kota Bekerja Sekarang', 'Alamat Kost/Mess', 'No Kontak Warga'] },
  { name: 'Surat Keterangan Persil', code: 'SKP-PSL', category: 'Surat Keterangan', fields: ['No Persil', 'Kelas Tanah (D/S/I/II)', 'Luas Persil'] },
  { name: 'Surat Keterangan Riwayat Tanah dan Bebas Sengketa', code: 'SKRTS', category: 'Surat Keterangan', fields: ['Silsilah Kepemilikan Lahan', 'Keterangan Segel/Sertifikat', 'Tanda Batas Batas'] },
  { name: 'Surat Keterangan Izin Bepergian', code: 'SKIB', category: 'Surat Keterangan', fields: ['Kota Tujuan', 'Waktu Kepergian', 'Keterangan Kepentingan'] },

  // --- LAINNYA ---
  { name: 'Surat Pernyataan Status', code: 'SPS', category: 'Lainnya', fields: ['Status Kawin Rinci (Duda/Janda/Lajang)', 'Saksi Kunci'] },
  { name: 'Surat Rekomendasi Nikah Kurang 10 Hari', code: 'SRN', category: 'Lainnya', fields: ['Nama Calon Istri/Suami', 'Alasan Mendesak Nikah', 'Lokasi Pernikahan'] },
  { name: 'Surat Persetujuan Mempelai', code: 'SPM-M', category: 'Lainnya', fields: ['Nama Calon Pengantin Pria', 'Nama Calon Pengantin Wanita'] },
  { name: 'Daftar Persyaratan Pernikahan (Kemenag)', code: 'DPP-K', category: 'Lainnya', fields: ['Keperluan Bimbingan', 'Dokumen Terlampir'] },
  { name: 'Surat Pengantar Permohonan SKCK', code: 'SP-SKCK', category: 'Lainnya', fields: ['Tujuan Pengajuan SKCK', 'Alamat Polsek/Polres', 'Catatan Kelakuan Baik'] },
  { name: 'Surat Pengantar SKCK', code: 'SPSKCK-L', category: 'Lainnya', fields: ['Tujuan SKCK', 'Klarifikasi Kelakuan Baik Desa'] },
  { name: 'Surat Permohonan KTP', code: 'SP-KTP', category: 'Lainnya', fields: ['Alasan Pembuatan KTP (Baru/Rusak/Hilang)', 'Nomor KK Terkait'] },
  { name: 'Surat Permohonan KK', code: 'SP-KK', category: 'Lainnya', fields: ['Alasan Pembuatan KK (Pecah/Hilang/Baru)', 'Daftar Anggota Keluarga'] },
  { name: 'Surat Permohonan Perubahan KK', code: 'SPP-KK', category: 'Lainnya', fields: ['Nama Anggota Diubah', 'Elemen Data yang Diubah', 'Dasar Perubahan'] },
  { name: 'Daftar Usia Sekolah PAUD', code: 'DUS-PAUD', category: 'Lainnya', fields: ['Nama PAUD Desa', 'Jumlah Siswa Terdata', 'Mulai Pembelajaran'] },
  { name: 'Daftar Usia Sekolah Taman Kanak-kanak (TK)', code: 'DUS-TK', category: 'Lainnya', fields: ['Nama TK', 'Kepala Sekolah TK', 'Tahun Ajaran'] },
  { name: 'Daftar Usia Sekolah Dasar', code: 'DUS-SD', category: 'Lainnya', fields: ['Tahun Ajaran Berjalan', 'Jumlah anak usia 7-12 tahun di Desa'] },
  { name: 'Daftar Usia Sekolah Menengah Pertama', code: 'DUS-SMP', category: 'Lainnya', fields: ['Tahun Ajaran', 'Jumlah anak usia 13-15 tahun terdata'] },
  { name: 'Daftar Usia Sekolah Menengah Atas/Kejuruan', code: 'DUS-SMA', category: 'Lainnya', fields: ['Tahun Ajaran', 'Jumlah anak usia 16-18 tahun terdata'] },
  { name: 'Buku Data Usia Pendidikan SD/SLTP/SLTA', code: 'BDUP', category: 'Lainnya', fields: ['Total Keseluruhan Siswa', 'Bantuan KIP Terdistribusi', 'Keterangan Putus Sekolah'] },

  // --- SURAT KUASA & ADMINISTRASI ---
  { name: 'Surat Kuasa', code: 'SKUAS', category: 'Surat Kuasa & Administrasi', fields: ['Nama Penerima Kuasa', 'NIK Penerima Kuasa', 'Uraian Kuasa yang Diberikan'] },
  { name: 'Kutipan dari Buku C Desa/Kelurahan', code: 'KBC-DESA', category: 'Surat Kuasa & Administrasi', fields: ['Nomor Buku C', 'Kelas Klasifikasi', 'Luas Total Tanah'] },
  { name: 'Surat Undangan', code: 'SUND', category: 'Surat Kuasa & Administrasi', fields: ['Acara/Agenda Kegiatan', 'Waktu Undangan Resmi', 'Lokasi Pertemuan Desa'] },
  { name: 'Surat Keabsahan Data', code: 'SKD-SAH', category: 'Surat Kuasa & Administrasi', fields: ['Uraian Data yang Diperiksa', 'Dasar Pembuktian', 'Tanda Tangan verifikator'] },
  { name: 'Form Permohonan Akta Kelahiran', code: 'FP-AK', category: 'Surat Kuasa & Administrasi', fields: ['Nama Bayi', 'Nama Saksi Lahir 1', 'Nama Saksi Lahir 2'] },
  { name: 'Biodata Penduduk Warga Negara Indonesia', code: 'BP-WNI', category: 'Surat Kuasa & Administrasi', fields: ['NIK Penduduk', 'Kepala Keluarga', 'Golongan Darah'] },
  { name: 'Formulir Pelaporan Kematian', code: 'FP-KM', category: 'Surat Kuasa & Administrasi', fields: ['Sebab Kematian Rinci', 'Menghubungi Dokter/Tidak', 'Dinas Terlapor'] },
  { name: 'Surat Pernyataan Kehilangan', code: 'SP-KHL', category: 'Surat Kuasa & Administrasi', fields: ['Daftar Berkas yang Hilang', 'Tanggal Kehilangan Kejadian'] },
  { name: 'Surat Pencatatan Itsbat', code: 'SP-ITS', category: 'Surat Kuasa & Administrasi', fields: ['Pengadilan Agama Pengambil Keputusan', 'No Putusan Itsbat', 'Tanggal Sidang'] },
  { name: 'Surat Pencatatan Permohonan Wali Hakim', code: 'SP-WH', category: 'Surat Kuasa & Administrasi', fields: ['Nama Calon Istri', 'Nama Calon Suami', 'Sebab Tidak Ada Wali Nasab'] },
  { name: 'Surat Pencatatan Permohonan Wali Masafatul Qosri', code: 'SP-WMQ', category: 'Surat Kuasa & Administrasi', fields: ['Nama Mempelai', 'Jarak Tempuh Wali Nasab (KM)', 'Wali Hakim Alternatif'] },
  { name: 'Surat Pencatatan Permohonan Wali Ghoib', code: 'SP-WG', category: 'Surat Kuasa & Administrasi', fields: ['Nama Wali Nasab Ghoib', 'Status Keberadaan Wali', 'Keterangan Pengadilan'] },
  { name: 'Berita Acara Pemeriksaan Wali', code: 'BAP-W', category: 'Surat Kuasa & Administrasi', fields: ['Tim Pemeriksa Desa', 'Hasil Verifikasi Status Wali', 'Saksi-Saksi'] },
  { name: 'Surat Pernyatan Perubahan Elemen Data Kependudukan', code: 'SPPEDK', category: 'Surat Kuasa & Administrasi', fields: ['Elemen Data Lama', 'Data Baru yang Benar', 'No Lampiran Bukti'] }
];
